initial accelsim traing branch
sarchlab/mgpusim pull request #28
Opened 2023-12-02 20:49 UTC by gongchen618

did some refactor, make the trace data flow through, no output

2023-12-02 20:56 UTC, gongchen618 commented
😮I think the lint test isn't working, I definitely cannot pass.

2023-12-02 23:34 UTC, syifan commented
> 😮I think the lint test isn't working, I definitely cannot pass.

Actually, all the tests passed. So, there is no linting issue.

2023-12-02 23:38 UTC, syifan requested changes

2023-12-02 23:38 UTC, syifan commented on acceclsim_tracing/gpc/README.md
> +接收来自 GPU 的任务分配，并且把若干个 threadblock 扔给一个 SM
Please do not write Chinese.

2023-12-02 23:38 UTC, syifan commented on acceclsim_tracing/example/bfs-rodinia-2.0-ft/kernel-1.traceg
These example trace files are taking many lines of code. Shall we remove them from here and put it on somewhere like Amazon S3?

2023-12-02 23:38 UTC, syifan commented
@gongchen618 Since this is a PR that only adds new code, should I just merge it, and let's talk about how to improve it later?

2023-12-03 03:50 UTC, gongchen618 commented on acceclsim_tracing/gpc/README.md
> +接收来自 GPU 的任务分配，并且把若干个 threadblock 扔给一个 SM
oh sorry, I write it to note myself but forget to delete it.

2023-12-03 03:50 UTC, gongchen618 commented on acceclsim_tracing/example/bfs-rodinia-2.0-ft/kernel-1.traceg
yes, lets remove it.

2023-12-03 03:57 UTC, gongchen618 commented
> @gongchen618 Since this is a PR that only adds new code, should I just merge it, and let's talk about how to improve it later?

Lets talk! I myself also have some coding problems that I keep doubting how to solve and I need your help 😿

2023-12-06 14:04 UTC, syifan commented on acceclsim_tracing/gpu/builder.go
> +		g.gpcs[i] = gpc.NewGPC().WithSMNum(g.meta.smNum).WithSMUnitNum(g.meta.smUnitNum).
One line per with-function

2023-12-06 14:05 UTC, syifan commented on acceclsim_tracing/trace/convert.go
> +	for _, wp := range tb.warps {
Empty line before for loop

2023-12-06 14:06 UTC, syifan commented on acceclsim_tracing/trace/convert.go
> +	return nvtb
Empty line before return

2023-12-06 19:48 UTC, syifan approved these changes

2023-12-06 19:49 UTC, syifan submitted a review, later dismissed

2023-12-13 14:07 UTC, syifan submitted a review, later dismissed

2023-12-13 14:08 UTC, merged